Wed/KTralan2/TestKT2/TestKT2/ViewComponents/TenSachViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using TestKT2.Models;

namespace TestKT2.ViewComponents
{
	public class TenSachViewComponent : ViewComponent
	{
		QlthuVienContext db = new QlthuVienContext();
		public IViewComponentResult Invoke()
		{
			var tloaisach = db.TLoaiSaches.ToList();
			return View("Default", tloaisach);

		}
	}
}

Wed/KTralan2/TestKT2/TestKT2/Views/Shared/Footer.cshtml
<div class="footer">
	<div class="wrap">
		<div class="copy_right">
			<p>Copy rights (c). All rights Reseverd | Template by  <a href="http://w3layouts.com" target="_blank">W3Layouts</a> </p>
		</div>
		<div class="footer-nav">
			<ul>
				<li><a href="#">Terms of Use</a> : </li>
				<li><a href="#">Privacy Policy</a> : </li>
				<li><a href="contact.html">Contact Us</a> : </li>
				<li><a href="#">Sitemap</a></li>
			</ul>
		</div>
	</div>
</div>

Wed/KTralan2/TestKT2/TestKT2/Views/Shared/Header.cshtml
<div class="navigation">
	<a class="toggleMenu" href="#">Menu</a>
	<ul class="nav">
		<li>
			@await Component.InvokeAsync("TenSach")
		</li>
		
	</ul>
	<span class="left-ribbon"> </span>
	<span class="right-ribbon"> </span>
</div>

Wed/KTralan2/TestKT2/TestKT2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TestKT2</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/TestKT2.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">TestKT2</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - TestKT2 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Wed/KTralan2/TestKT2/TestKT2/Views/Shared/_LayoutIndex.cshtml
<!--A Design by W3layouts
Author: W3layout
Author URL: http://w3layouts.com
License: Creative Commons Attribution 3.0 Unported
License URL: http://creativecommons.org/licenses/by/3.0/
-->
<!DOCTYPE HTML>
<head>
	<title>Free Ecomm Template Website Template | Home :: w3layouts</title>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
	<link href='http://fonts.googleapis.com/css?family=Ubuntu+Condensed' rel='stylesheet' type='text/css'>
	<link href="../Layout/css/style.css" rel="stylesheet" type="text/css" media="all" />
	<script type="text/javascript" src="../Layout/js/jquery-1.9.0.min.js"></script>
	<script src="../Layout/js/jquery.openCarousel.js" type="text/javascript"></script>
	<script type="text/javascript" src="../Layout/js/easing.js"></script>
	<script type="text/javascript" src="../Layout/js/move-top.js"></script>
</head>
<body>
	<div class="header">
		<div class="wrap">
			<div class="header_top">
				<div class="logo">
					<a href="index.html"><img src="../Layout/images/logo.png" alt="" /></a>
				</div>
				<div class="header_top_right">
					<div class="search_box">
						<span>Search</span>
						<form>
							<input type="text" value=""><input type="submit" value="">
						</form>
						<div class="clear"></div>
					</div>
				</div>
				<div class="clear"></div>
			</div>
			@Html.Partial("Header")
			<div class="header_bottom">
				<div class="slider-text">
					<h2>Lorem Ipsum Placerat <br />Elementum Quistue Tunulla Maris</h2>
					<p>Vivamus vitae augue at quam frigilla tristique sit amet<br /> acin ante sikumpre tisdin.</p>
					<a href="#">Sitamet Tortorions</a>
				</div>
				<div class="slider-img">
					<img src="../Layout/images/slider-img.png" alt="" />
				</div>
				<div class="clear"></div>
			</div>
		</div>
	</div>
	<!------------End Header ------------>
	<div class="main">
		<div class="content">
			<div class="content_top">
				<div class="wrap">
					<h3>Latest Products</h3>
				</div>
				<div class="line"> </div>
				<div class="wrap">
					<div class="ocarousel_slider">
						<div class="ocarousel example_photos" data-ocarousel-perscroll="3">
							<div class="ocarousel_window">
								<a href="#" title="img1"> <img src="../Layout/images/latest-product-img1.jpg" alt="" /><p>Nuncvitae</p></a>
								<a href="#" title="img2"> <img src="../Layout/images/latest-product-img2.jpg" alt="" /><p>Suspendiss</p></a>
								<a href="#" title="img3"> <img src="../Layout/images/latest-product-img3.jpg" alt="" /><p>Phasellus ferm</p></a>
								<a href="#" title="img4"> <img src="../Layout/images/latest-product-img4.jpg" alt="" /><p>Veldignissim</p></a>
								<a href="#" title="img5"> <img src="../Layout/images/latest-product-img5.jpg" alt="" /><p>Aliquam interd</p></a>
								<a href="#" title="img6"> <img src="../Layout/images/latest-product-img6.jpg" alt="" /><p>Sapien lectus</p></a>
								<a href="#" title="img1"> <img src="../Layout/images/latest-product-img1.jpg" alt="" /><p>Nuncvitae</p></a>
								<a href="#" title="img2"> <img src="../Layout/images/latest-product-img2.jpg" alt="" /><p>Suspendiss</p></a>
								<a href="#" title="img3"> <img src="../Layout/images/latest-product-img3.jpg" alt="" /><p>Phasellus ferm</p></a>
								<a href="#" title="img4"> <img src="../Layout/images/latest-product-img4.jpg" alt="" /><p>Veldignissim</p></a>
								<a href="#" title="img5"> <img src="../Layout/images/latest-product-img5.jpg" alt="" /><p>Aliquam interd</p></a>
								<a href="#" title="img6"> <img src="../Layout/images/latest-product-img6.jpg" alt="" /><p>Sapien lectus</p></a>
							</div>
							<span>
								<a href="#" data-ocarousel-link="left" style="float: left;" class="prev"> </a>
								<a href="#" data-ocarousel-link="right" style="float: right;" class="next"> </a>
							</span>
						</div>
					</div>
				</div>
			</div>
			<div class="content_bottom">
				<div class="wrap">
					<div class="content-bottom-left">
						<div class="categories">
							<ul>
								<h3>Browse All Categories</h3>
								<li><a href="#">Appliances</a></li>
								<li><a href="#">Sports Equipments</a></li>
								<li><a href="#">Computers & Electronics</a></li>
								<li><a href="#">Office supplies</a></li>
								<li><a href="#">Health & Beauty</a></li>
								<li><a href="#">Home & Garden</a></li>
								<li><a href="#">Apparel</a></li>
								<li><a href="#">Toys & Games</a></li>
								<li><a href="#">Automotive</a></li>
							</ul>
						</div>
						<div class="buters-guide">
							<h3>Buyers Guide</h3>
							<p><span>We want you to be happy with your purchase.</span></p>
							<p>So we're committed to giving you all the tools to make the right decision with minimum fuss. </p>
						</div>
						<div class="add-banner">
							<img src="../Layout/images/camera.png" alt="" />
							<div class="banner-desc">
								<h4>Electronics</h4>
								<a href="#">More Info</a>
							</div>
							<div class="clear"></div>
						</div>
						<div class="add-banner add-banner2">
							<img src="../Layout/images/computer.png" alt="" />
							<div class="banner-desc">
								<h4>Computers</h4>
								<a href="#">More Info</a>
							</div>
							<div class="clear"></div>
						</div>
					</div>

					@RenderBody();
					<div class="clear"></div>
				</div>
			</div>
		</div>
	</div>
	@Html.Partial("Footer")
	<script type="text/javascript">
		$(document).ready(function() {
			$().UItoTop({ easingType: 'easeOutQuart' });

		});
	</script>
	<a href="#" id="toTop"> </a>
	<script type="text/javascript" src="../Layout/js/navigation.js"></script>
</body>
</html>